obstacle_range: 2.5
raytrace_range: 255
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
robot_radius: 10.0 # distance a circular robot should be clear of the obstacle
inflation_radius: 3.0

observation_sources: laser_scan_sensor point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: ego_vehicle/lidar/lidar1, data_type: LaserScan, topic: /camera/scan, marking: true, clearing: true}
point_cloud_sensor: {sensor_frame: ego_vehicle/lidar/lidar1, data_type: PointCloud2, topic: /carla/ego_vehicle/lidar/lidar1/point_cloud, marking: true, clearing: true}
