local_costmap:
  global_frame: map
  robot_base_frame: ego_vehicle
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 1000.0
  height: 1000.0
  resolution: 0.05
