(cl:defpackage carla_msgs-msg
  (:use )
  (:export
   "<CARLAACTORINFO>"
   "CARLAACTORINFO"
   "<CARLAACTORLIST>"
   "CARLAACTORLIST"
   "<CARLACOLLISIONEVENT>"
   "CARLACOLLISIONEVENT"
   "<CARLACONTROL>"
   "CARLACONTROL"
   "<CARLAEGOVEHICLECONTROL>"
   "CARLAEGOVEHICLECONTROL"
   "<CARLAEGOVEHICLEINFO>"
   "CARLAEGOVEHICLEINFO"
   "<CARLAEGOVEHICLEINFOWHEEL>"
   "CARLAEGOVEHICLEINFOWHEEL"
   "<CARLAEGOVEHICLESTATUS>"
   "CARLAEGOVEHICLESTATUS"
   "<CARLALANEINVASIONEVENT>"
   "CARLALANEINVASIONEVENT"
   "<CARLASTATUS>"
   "CARLASTATUS"
   "<CARLAWALKERCONTROL>"
   "CARLAWALKERCONTROL"
   "<CARLAWORLDINFO>"
   "CARLAWORLDINFO"
  ))

