// Generated by gencpp from file carla_msgs/CarlaCollisionEvent.msg
// DO NOT EDIT!


#ifndef CARLA_MSGS_MESSAGE_CARLACOLLISIONEVENT_H
#define CARLA_MSGS_MESSAGE_CARLACOLLISIONEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace carla_msgs
{
template <class ContainerAllocator>
struct CarlaCollisionEvent_
{
  typedef CarlaCollisionEvent_<ContainerAllocator> Type;

  CarlaCollisionEvent_()
    : header()
    , other_actor_id(0)
    , normal_impulse()  {
    }
  CarlaCollisionEvent_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , other_actor_id(0)
    , normal_impulse(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _other_actor_id_type;
  _other_actor_id_type other_actor_id;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_impulse_type;
  _normal_impulse_type normal_impulse;





  typedef boost::shared_ptr< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> const> ConstPtr;

}; // struct CarlaCollisionEvent_

typedef ::carla_msgs::CarlaCollisionEvent_<std::allocator<void> > CarlaCollisionEvent;

typedef boost::shared_ptr< ::carla_msgs::CarlaCollisionEvent > CarlaCollisionEventPtr;
typedef boost::shared_ptr< ::carla_msgs::CarlaCollisionEvent const> CarlaCollisionEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator1> & lhs, const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.other_actor_id == rhs.other_actor_id &&
    lhs.normal_impulse == rhs.normal_impulse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator1> & lhs, const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f08ee4a25bac7157d460b45684dd2b7";
  }

  static const char* value(const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f08ee4a25bac715ULL;
  static const uint64_t static_value2 = 0x7d460b45684dd2b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_msgs/CarlaCollisionEvent";
  }

  static const char* value(const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# Copyright (c) 2019 Intel Corporation.\n"
"#\n"
"# This work is licensed under the terms of the MIT license.\n"
"# For a copy, see <https://opensource.org/licenses/MIT>.\n"
"#\n"
"# A collision event\n"
"\n"
"Header header\n"
"\n"
"uint32 other_actor_id\n"
"geometry_msgs/Vector3 normal_impulse\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.other_actor_id);
      stream.next(m.normal_impulse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarlaCollisionEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_msgs::CarlaCollisionEvent_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "other_actor_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.other_actor_id);
    s << indent << "normal_impulse: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal_impulse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_MSGS_MESSAGE_CARLACOLLISIONEVENT_H
