# static_map - True if using existing map

global_costmap:
  global_frame: map
  robot_base_frame: ego_vehicle
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: false
  width: 1000.0
  height: 1000.0
